DEV: Add summarization logic from core
discourse/discourse-ai pull request #658
Opened 2024-06-06 21:39 UTC by keegangeorge

This PR adds summarization logic back to the plugin from core. See core PR: https://github.com/discourse/discourse/pull/27373

2024-06-10 17:44 UTC, romanrizzi requested changes

2024-06-10 17:44 UTC, romanrizzi commented on db/migrate/20240606152117_copy_summary_sections_to_ai_summaries.rb
> +class CopySummarySectionsToAiSummaries < ActiveRecord::Migration[7.0]
This should be under `post_migrate`, and it should be irreversible.

2024-06-10 17:44 UTC, romanrizzi commented on db/migrate/20240606151348_create_ai_summaries_table.rb
> +      t.integer :meta_section_id
We should drop this, and only migrate those where `meta_section_id` is null. This means they are the final summary shown to users. We never really use these small fragments so it's a good opportunity to get rid of them

2024-06-10 17:44 UTC, romanrizzi commented on config/settings.yml
> +  ai_summarization_strategy:
I think we are missing a way to migrate the old setting here? We don't want to break summaries

2024-06-10 17:44 UTC, romanrizzi commented on app/services/topic_summarization.rb
> +    result[:chunks].each do |chunk|
Dropping `meta_section_id` means we can simplify this

2024-06-13 19:40 UTC, romanrizzi commented on app/services/topic_summarization.rb
> +    result[:chunks].each do |chunk|
Yes, exactly

2024-06-27 17:14 UTC, xfalcox commented on db/post_migrate/20240610232546_copy_custom_summarization_allowed_groups_to_ai_custom_summarization_allowed_groups.rb
> +  7.0
lol

2024-06-27 20:00 UTC, romanrizzi requested changes

2024-06-27 20:00 UTC, romanrizzi commented on lib/summarization/entry_point.rb
> +          DiscoursePluginRegistry.register_summarization_strategy(
I think we can just return `foldable_models` in `Models::Base#available_strategies`? Nobody else consumes this register

2024-07-01 22:09 UTC, romanrizzi approved these changes

2024-07-02 15:52 UTC, merged